### ISSUE TITLE
Meta tags for topics and tags

### ISSUE THREAD

**Issue by Kajaia** [austintoddj/canvas#1432]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Will be good if you add new fields for topics and tags, where we can add meta title and description, or even image. That would be relly helpful for seo

### Validations

- [X] Follow our [Code of Conduct](https://github.com/austintoddj/canvas/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/austintoddj/canvas/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by austintoddj** [comment]
Closing as stale. Please check out [v7.0](https://github.com/austintoddj/canvas/releases/tag/v7.0.0) for the most up to date version of Canvas.
